# Generated by Django 4.1.7 on 2023-10-05 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TailoringService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('land', models.CharField(max_length=50)),
                ('straat', models.CharField(max_length=100)),
                ('huisnummer', models.CharField(max_length=10)),
                ('bus', models.CharField(max_length=10)),
                ('postcode', models.CharField(max_length=10)),
                ('stad', models.CharField(max_length=50)),
                ('productvoorraadnummer', models.CharField(blank=True, max_length=50, null=True)),
                ('jasmaat', models.IntegerField(blank=True, null=True)),
                ('vestmaat', models.IntegerField(blank=True, null=True)),
                ('broekmaat', models.IntegerField(blank=True, null=True)),
                ('wedding_date', models.DateField(blank=True, null=True)),
                ('is_pickup', models.BooleanField(default=False)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tailoring.location')),
                ('services', models.ManyToManyField(to='tailoring.tailoringservice')),
            ],
        ),
    ]
