# Generated by Django 4.1.7 on 2024-01-29 17:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TailoringService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('service_type', models.CharField(choices=[('', '---------'), ('Order', 'Order'), ('Tailoring', 'Tailoring Service')], default='', max_length=10)),
                ('tracking_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('order_ready', models.BooleanField(default=False)),
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('land', models.CharField(blank=True, max_length=50, null=True)),
                ('straat', models.CharField(blank=True, max_length=100, null=True)),
                ('huisnummer', models.CharField(blank=True, max_length=10, null=True)),
                ('bus', models.CharField(blank=True, max_length=10, null=True)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('stad', models.CharField(blank=True, max_length=50, null=True)),
                ('productvoorraadnummer', models.CharField(blank=True, max_length=50, null=True)),
                ('jasmaat', models.IntegerField(blank=True, null=True)),
                ('vestmaat', models.IntegerField(blank=True, null=True)),
                ('broekmaat', models.IntegerField(blank=True, null=True)),
                ('wedding_date', models.DateField(blank=True, null=True)),
                ('is_pickup', models.BooleanField(default=False)),
                ('email_content', models.TextField(blank=True, default='Your order has been prepared, please make your appointment via this link https://booking.appointy.com/nl-NL/pomandi/locations.', null=True)),
                ('sms_content', models.TextField(blank=True, default='Your order has been prepared, please make your appointment via this link https://booking.appointy.com/nl-NL/pomandi/locations.', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tailoring.location')),
                ('services', models.ManyToManyField(blank=True, to='tailoring.tailoringservice')),
            ],
        ),
    ]
