# Generated by Django 4.1.7 on 2023-10-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='sms_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
