# Generated by Django 4.1.7 on 2023-10-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailoring', '0002_customer_email_content_customer_sms_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email_content',
            field=models.TextField(blank=True, default='Varsayılan e-posta içeriği burada.', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sms_content',
            field=models.TextField(blank=True, default='Varsayılan SMS içeriği burada.', null=True),
        ),
    ]
