# Generated by Django 4.1.7 on 2023-10-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailoring', '0004_remove_customer_email_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_content',
            field=models.TextField(blank=True, default='Varsayılan e-posta içeriği burada.', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='sms_content',
            field=models.TextField(blank=True, default='Varsayılan SMS içeriği burada.', null=True),
        ),
    ]
