# Generated by Django 4.1.7 on 2023-10-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailoring', '0005_customer_email_content_customer_sms_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
