# Generated by Django 4.1.7 on 2023-10-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailoring', '0006_customer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='service_type',
            field=models.CharField(choices=[('siparis', 'Sipariş'), ('terzilik', 'Terzilik Hizmeti')], default='siparis', max_length=10),
        ),
    ]
