# Generated by Django 4.1.7 on 2023-10-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailoring', '0007_customer_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='service_type',
            field=models.CharField(choices=[('', '---------'), ('siparis', 'Sipariş'), ('terzilik', 'Terzilik Hizmeti')], default='', max_length=10),
        ),
    ]
