# Generated by Django 4.1.7 on 2023-10-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailoring', '0008_alter_customer_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bus',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='huisnummer',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='land',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='service_type',
            field=models.CharField(choices=[('', '---------'), ('siparis', 'Order'), ('terzilik', 'Tailoring Service')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='stad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='straat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
