# Generated by Django 4.1.7 on 2024-01-29 16:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tailoring', '0010_alter_customer_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='order_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='tracking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email_content',
            field=models.TextField(blank=True, default='Your order has been prepared, please make your appointment via this link https://booking.appointy.com/nl-NL/pomandi/locations.', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='service_type',
            field=models.CharField(choices=[('', '---------'), ('Order', 'Order'), ('Tailoring', 'Tailoring Service')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sms_content',
            field=models.TextField(blank=True, default='Your order has been prepared, please make your appointment via this link https://booking.appointy.com/nl-NL/pomandi/locations.', null=True),
        ),
    ]
