# Generated by Django 4.1.7 on 2023-10-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailoring', '0010_alter_customer_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email_content',
            field=models.TextField(blank=True, default='Your order has been prepared, please make your appointment via this link https://booking.appointy.com/nl-NL/pomandi/locations.', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sms_content',
            field=models.TextField(blank=True, default='Your order has been prepared, please make your appointment via this link https://booking.appointy.com/nl-NL/pomandi/locations.', null=True),
        ),
    ]
