# Generated by Django 4.1.7 on 2024-01-29 16:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tailoring', '0011_alter_customer_email_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='order_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='tracking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='service_type',
            field=models.CharField(choices=[('', '---------'), ('Order', 'Order'), ('Tailoring', 'Tailoring Service')], default='', max_length=10),
        ),
    ]
