# Generated by Django 4.1.7 on 2024-01-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailoring', '0011_customer_order_ready_customer_tracking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='test_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
