# Generated by Django 4.1.7 on 2024-01-29 10:42

from django.db import migrations, models
import uuid

def create_uuid(apps, schema_editor):
    Customer = apps.get_model('tailoring', 'Customer')
    for customer in Customer.objects.filter(tracking_id__isnull=True):
        customer.tracking_id = uuid.uuid4()
        customer.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tailoring', '0013_customer_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tracking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='customer',
            name='tracking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]