# Generated by Django 4.1.7 on 2024-01-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailoring', '0015_alter_customer_tracking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='tracking_id',
        ),
    ]
