# Generated by Django 4.1.7 on 2024-01-29 11:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tailoring', '0016_remove_customer_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tracking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
