# Generated by Django 4.1.7 on 2024-01-29 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailoring', '0018_auto_20240129_1216'),
    ]

    operations = [
    ]
