# Generated by Django 4.1.7 on 2024-01-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailoring', '0019_auto_20240129_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='service_type',
            field=models.CharField(choices=[('', '---------'), ('Order', 'Order'), ('Tailoring', 'Tailoring Service')], default='', max_length=10),
        ),
    ]
