# Generated by Django 4.1.7 on 2024-01-29 16:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tailoring', '0020_alter_customer_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tracking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
